import './globals.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';

import { SocketProvider } from "@/components/providers/socket-provider";
import ModelProviders from "@/components/providers/model-providers";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import QueryProvider from "@/components/providers/query-provider";

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }} >
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={true} >
        <SocketProvider>
        <ModelProviders />          
       <QueryProvider>
       {children}
       </QueryProvider>
        </SocketProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
    </ClerkProvider>
  )
}
